### ISSUE TITLE
Update for Xcode 8.3

### ISSUE THREAD

**Issue by AvdLee** [soheilbm/Firebase#11]
Currently Firebase contains warnings in Xcode 8.3 as discussed in [this](http://stackoverflow.com/questions/42268117/how-to-remove-the-xcode-warning-apple-mach-o-linker-warning-pointer-not-aligned) thread. 

Google points out they're working on a update, which should be included in this repo (as normal of course).

Created this issue to keep track of this.

3.15.0 is already released and not included here yet, but is not fixing this issue as pointed out in the SO thread:
> Firebase has fixed the issue and we are preparing a release. We also have checked if the warning messages represent a real problem and we found no issue associated with them. Sorry for the inconvenience.
_March 31_

**Comment by bennokress** [comment]
3.16.0 of the official Firebase is out and should fix the issue. Would be nice, if it could be updated here as well :)

**Comment by AvdLee** [comment]
@bennokress I've created a PR #13 which fixes this. You can already use my fork if you want.
