### ISSUE TITLE
3.17.0 release

### ISSUE THREAD

**Issue by tbaranes** [soheilbm/Firebase#14]
Would be great to have a new release including the last version of firebase

**Comment by Gujci** [comment]
Will this include `FirebasePerformance` module? Or any plans adding that?

**Comment by soheilbm** [comment]
@tbaranes @Gujci I skipped version 3.17.0 but I added [4.0.4](https://github.com/soheilbm/Firebase/tree/4.0.4). I will merge it after I update the readme. Please try it.

**Comment by Gujci** [comment]
@soheilbm tried it, thanks 👌
