### ISSUE TITLE
Can't install app if it has firebase framework

### ISSUE THREAD

**Issue by matghazaryan** [soheilbm/Firebase#18]
When I am integrating Firebase as Carthage and I am sending build via Fabric application not installing at all. 
When  I am removing Firebase everything working as expected.
I have created carthage framework and insert it yo my project following files.
1. Firebase
2. FirebaseCore
3. FirebaseMessaging

Is there any kind of problem here?

**Comment by soheilbm** [comment]
If you follow the instruction in readme you need to add below frameworks: 

- FirebaseAnalytics.framework
- FirebaseCore.framework
- FirebaseCoreDiagnostics.framework
- FirebaseNanoPB.framework
- FirebaseInstanceID.framework
- GoogleToolboxForMac.framework
- nanopb.framework
- FirebaseMessaging.framework
- Protobuf.framework
