### ISSUE TITLE
Apple Match-O Linker (Id) Error

### ISSUE THREAD

**Issue by maysamsh** [soheilbm/Firebase#26]
I've done exactly what you wrote but I get this error (for FirebaseAuth):

> Undefined symbols for architecture arm64:
>   "_FIRAuthStateDidChangeInternalNotification", referenced from:
>       ___50-[FIRAuth possiblyPostAuthStateChangeNotification]_block_invoke in FirebaseAuth(FIRAuth_d3345993aebdf1a4605c6b15c3385d2b.o)
>   "_FIRAuthStateDidChangeInternalNotificationAppKey", referenced from:
>       -[FIRAuth possiblyPostAuthStateChangeNotification] in FirebaseAuth(FIRAuth_d3345993aebdf1a4605c6b15c3385d2b.o)
>   "_FIRAuthStateDidChangeInternalNotificationTokenKey", referenced from:
>       -[FIRAuth possiblyPostAuthStateChangeNotification] in FirebaseAuth(FIRAuth_d3345993aebdf1a4605c6b15c3385d2b.o)
> ld: symbol(s) not found for architecture arm64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)

<img width="423" alt="screenshot at nov 15 14-11-15" src="https://user-images.githubusercontent.com/2828697/32831847-dc5ddd08-ca0e-11e7-8fef-7c9a59eb4a44.png">

<img width="391" alt="screenshot at nov 15 14-01-56" src="https://user-images.githubusercontent.com/2828697/32831479-b3998b02-ca0d-11e7-983f-a50f6b1b33e8.png">

<img width="412" alt="screenshot at nov 15 14-05-08" src="https://user-images.githubusercontent.com/2828697/32831580-07352988-ca0e-11e7-8796-a61637bb3115.png">

**Comment by SzymonMrozek** [comment]
Same here

**Comment by maysamsh** [comment]
I gave up and used the released `.framework` files. It works fine.

**Comment by SzymonMrozek** [comment]
What do you mean?

**Comment by tbaranes** [comment]
I'm getting the same issue, @maysamsh interesting too by your solution if you can explain it.

**Comment by SzymonMrozek** [comment]
The solution was to add it without using this repo 😄

**Comment by maysamsh** [comment]
@tbaranes Just add it manually, follow this https://firebase.google.com/docs/ios/setup

**Comment by tbaranes** [comment]
Got it, I tried this as well, but still having the issue... 😑

**Comment by maysamsh** [comment]
@tbaranes What about my trick? delete the Info.plist, and drag it to your project from another project.

**Comment by tbaranes** [comment]
Not sure how that would help, but it didn't work. One thing that may be different from the usual cases, I'm adding Firebase to a framework target instead of the app one, but I don't see why it won't work this way.

**Comment by tbaranes** [comment]
I finally get it working by mixing the instructions from this repository and the manual one from firebase. Not really sure why is it working now and not before, but, well, it's working.

Closing since everyone seems to have find a way to make it work!
