### ISSUE TITLE
carthage copy-framework fails

### ISSUE THREAD

**Issue by leonereveel** [soheilbm/Firebase#4]
When I execute `carthage copy-frameworks`, I'm getting this error:

```
Failed to read file or folder at  ${SRC_ROOT}/Carthage/Build/iOS/FirebaseAnalytics.framework
```

I found out, according to this issue https://github.com/Carthage/Carthage/issues/1079, that carthage check for a Info.plist file inside each framework. 

How do you embed the framework inside your project without `carthage copy-frameworks`?

**Comment by ruudk** [comment]
Did you get it working? I am having struggles with implementing Firebase via Carthage too. I cannot get it to work.

**Comment by soheilbm** [comment]
May I know which xcode version are you using? 
I only tested this with xCode 8.0 and swift 3.0

**Comment by ruudk** [comment]
For me Xcode 8.2 and Swift 3.0

**Comment by jussi-laitinen** [comment]
Everything is working for me when I run the app on the simulator or on the phone. But when I try to archive the app I get the following error:

> Invalid architecture UUIDs: Could not parse UUIDs using dwarfdump

@soheilbm Have you tried to archive an app using this dependency and does it work?

**Comment by soheilbm** [comment]
@jsslai I'm already using it for production. Are you using carthage **copy Framework** script as well? https://github.com/Carthage/Carthage#getting-started

**Comment by jussi-laitinen** [comment]
@soheilbm Yeah I also have other dependencies used with Carthage and they are working. I ended up adding Firebase static framework manually. I guess there was something wrong with my setup (app + framework which uses Firebase). Maybe I forget to include every Firebase dependency in my app target.

**Comment by maguro** [comment]
I'm running into the same issue.  It seems that the `copy-frameworks` script requires `Info.plist` files in order to work.  I'm not quite sure how this is working for you @soheilbm.  Could your projects be set up differently?

In any case, the solution is simple, add the missing `Info.plist` files.  I'm happy to submit a PR.

**Comment by soheilbm** [comment]
@maguro I added those libraries without **info.plist** inside the linked library in xcode. And those with info.plist I added them to copy-framework script. 

I've been quite busy lately but if you can submit a pr it would be great. 👍
