### ISSUE TITLE
+[NSData gtm_dataByGzippingData:error:]

### ISSUE THREAD

**Issue by anitalanet** [soheilbm/Firebase#7]
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[NSData gtm_dataByGzippingData:error:]: unrecognized selector sent to class 0x1100462e8'

App crash when we initialize Firebase Core

Can you please fix it?

I have added the linker flag -ObjC in my build setting

**Comment by soheilbm** [comment]
you need to add this into your libraries: 
- libc++.tbd
- libsqlite3.tbd
- AddressBook.framework

**Comment by brianlenz** [comment]
I wonder if this is also related to #10.
