### ISSUE TITLE
Firebase added keyChain internally whit <5f70666f> key

### ISSUE THREAD

**Issue by anitalanet** [soheilbm/Firebase#8]
Hi there

I am using firebase in my app
I am also use keychain in my app, but the issue is  when i am initialize firebase like [FIRApp configure]; it add one keychain internally but the key is like <5f70666f> and when i ittrate my keychain it create the crashes

       acct = <5f70666f>;
        agrp = "99P5TJ23MZ.com.xyzmyProj.com";
        cdat = "2017-03-09 09:05:10 +0000";
        gena = <5f70666f>;
        mdat = "2017-03-09 09:05:10 +0000";
        musr = <>;
        pdmn = dku;
        svce = "com.xyzmyProj.com";
        sync = 0;
        tomb = 0;

but when i comment [FIRApp configure], it want added the object/item in keychain

Can you please fix it ?

**Comment by soheilbm** [comment]
I can't replicate this, do you have a sample project that I could try?
