### ISSUE TITLE
Issue when build project and call FIRApp.configure()

### ISSUE THREAD

**Issue by kulakoff83** [soheilbm/Firebase#9]
`Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_GSDK_PBGeneratedEnumDescriptor", referenced from:
      _OBJC_CLASS_$_FIR_CLEARCUTLogEvent_InternalEventEnumDescriptor in FirebaseAnalytics(ClientanalyticsStripped.pb_aa94bc5179ca8a14f130d6f5ee5a3c26.o)
      _OBJC_CLASS_$_FIR_CLEARCUTNetworkConnectionInfo_NetworkTypeEnumDescriptor in FirebaseAnalytics(ClientanalyticsStripped.pb_aa94bc5179ca8a14f130d6f5ee5a3c26.o)
      _OBJC_CLASS_$_FIR_CLEARCUTPancettaClientInfo_OsTypeEnumDescriptor in FirebaseAnalytics(ClientanalyticsStripped.pb_aa94bc5179ca8a14f130d6f5ee5a3c26.o)
      _OBJC_CLASS_$_FIR_CLEARCUTVrClientInfo_VrClientTypeEnumDescriptor in FirebaseAnalytics(ClientanalyticsStripped.pb_aa94bc5179ca8a14f130d6f5ee5a3c26.o)
      _OBJC_CLASS_$_FIR_CLEARCUTJsClientInfo_DeviceTypeEnumDescriptor in FirebaseAnalytics(ClientanalyticsStripped.pb_aa94bc5179ca8a14f130d6f5ee5a3c26.o)
      _OBJC_CLASS_$_FIR_CLEARCUTClientInfo_ClientTypeEnumDescriptor in FirebaseAnalytics(ClientanalyticsStripped.pb_aa94bc5179ca8a14f130d6f5ee5a3c26.o)
      _OBJC_CLASS_$_FIR_CLEARCUTLogRequest_LogSourceEnumDescriptor in FirebaseAnalytics(ClientanalyticsStripped.pb_aa94bc5179ca8a14f130d6f5ee5a3c26.o)
      ...
  "_OBJC_CLASS_$_GSDK_PBDescriptor", referenced from:
      objc-class-ref in FirebaseAnalytics(ClientanalyticsStripped.pb_aa94bc5179ca8a14f130d6f5ee5a3c26.o)
      objc-class-ref in FirebaseAnalytics(GmpAudience.pb_d68254ec585824fa42de6de2f056cda0.o)
      objc-class-ref in FirebaseAnalytics(GmpConfig.pb_ab1145dc8be746cf062deaba528d2d30.o)
      objc-class-ref in FirebaseAnalytics(GmpMeasurement.pb_20d3abd5a5d905507f0986bcf4a2d72c.o)
      objc-class-ref in FirebaseAnalytics(IcoreStripped.pb_3e848749575206f4cf5f115ea38a4ebe.o)
  "_OBJC_CLASS_$_GSDK_PBEnumDescriptor", referenced from:
      objc-class-ref in FirebaseAnalytics(ClientanalyticsStripped.pb_aa94bc5179ca8a14f130d6f5ee5a3c26.o)
      objc-class-ref in FirebaseAnalytics(GmpAudience.pb_d68254ec585824fa42de6de2f056cda0.o)
      objc-class-ref in FirebaseAnalytics(IcoreStripped.pb_3e848749575206f4cf5f115ea38a4ebe.o)
  "_OBJC_METACLASS_$_GSDK_PBGeneratedMessage", referenced from:
      _OBJC_METACLASS_$_FIR_CLEARCUTLogEventKeyValues in FirebaseAnalytics(ClientanalyticsStripped.pb_aa94bc5179ca8a14f130d6f5ee5a3c26.o)
      _OBJC_METACLASS_$_FIR_CLEARCUTActiveExperiments in FirebaseAnalytics(ClientanalyticsStripped.pb_aa94bc5179ca8a14f130d6f5ee5a3c26.o)
      _OBJC_METACLASS_$_FIR_CLEARCUTLogEvent in FirebaseAnalytics(ClientanalyticsStripped.pb_aa94bc5179ca8a14f130d6f5ee5a3c26.o)
      _OBJC_METACLASS_$_FIR_CLEARCUTNetworkConnectionInfo in FirebaseAnalytics(ClientanalyticsStripped.pb_aa94bc5179ca8a14f130d6f5ee5a3c26.o)
      _OBJC_METACLASS_$_FIR_CLEARCUTExperimentIds in FirebaseAnalytics(ClientanalyticsStripped.pb_aa94bc5179ca8a14f130d6f5ee5a3c26.o)
      _OBJC_METACLASS_$_FIR_CLEARCUTAndroidClientInfo in FirebaseAnalytics(ClientanalyticsStripped.pb_aa94bc5179ca8a14f130d6f5ee5a3c26.o)
      _OBJC_METACLASS_$_FIR_CLEARCUTBrowserInfo in FirebaseAnalytics(ClientanalyticsStripped.pb_aa94bc5179ca8a14f130d6f5ee5a3c26.o)
      ...
  "_OBJC_CLASS_$_GSDK_PBGeneratedMessage", referenced from:
      _OBJC_CLASS_$_FIR_CLEARCUTLogEventKeyValues in FirebaseAnalytics(ClientanalyticsStripped.pb_aa94bc5179ca8a14f130d6f5ee5a3c26.o)
      _OBJC_CLASS_$_FIR_CLEARCUTActiveExperiments in FirebaseAnalytics(ClientanalyticsStripped.pb_aa94bc5179ca8a14f130d6f5ee5a3c26.o)
      _OBJC_CLASS_$_FIR_CLEARCUTLogEvent in FirebaseAnalytics(ClientanalyticsStripped.pb_aa94bc5179ca8a14f130d6f5ee5a3c26.o)
      _OBJC_CLASS_$_FIR_CLEARCUTNetworkConnectionInfo in FirebaseAnalytics(ClientanalyticsStripped.pb_aa94bc5179ca8a14f130d6f5ee5a3c26.o)
      _OBJC_CLASS_$_FIR_CLEARCUTExperimentIds in FirebaseAnalytics(ClientanalyticsStripped.pb_aa94bc5179ca8a14f130d6f5ee5a3c26.o)
      _OBJC_CLASS_$_FIR_CLEARCUTAndroidClientInfo in FirebaseAnalytics(ClientanalyticsStripped.pb_aa94bc5179ca8a14f130d6f5ee5a3c26.o)
      _OBJC_CLASS_$_FIR_CLEARCUTBrowserInfo in FirebaseAnalytics(ClientanalyticsStripped.pb_aa94bc5179ca8a14f130d6f5ee5a3c26.o)
      ...
  "_OBJC_METACLASS_$_GSDK_PBGeneratedEnumDescriptor", referenced from:
      _OBJC_METACLASS_$_FIR_CLEARCUTLogEvent_InternalEventEnumDescriptor in FirebaseAnalytics(ClientanalyticsStripped.pb_aa94bc5179ca8a14f130d6f5ee5a3c26.o)
      _OBJC_METACLASS_$_FIR_CLEARCUTNetworkConnectionInfo_NetworkTypeEnumDescriptor in FirebaseAnalytics(ClientanalyticsStripped.pb_aa94bc5179ca8a14f130d6f5ee5a3c26.o)
      _OBJC_METACLASS_$_FIR_CLEARCUTPancettaClientInfo_OsTypeEnumDescriptor in FirebaseAnalytics(ClientanalyticsStripped.pb_aa94bc5179ca8a14f130d6f5ee5a3c26.o)
      _OBJC_METACLASS_$_FIR_CLEARCUTVrClientInfo_VrClientTypeEnumDescriptor in FirebaseAnalytics(ClientanalyticsStripped.pb_aa94bc5179ca8a14f130d6f5ee5a3c26.o)
      _OBJC_METACLASS_$_FIR_CLEARCUTJsClientInfo_DeviceTypeEnumDescriptor in FirebaseAnalytics(ClientanalyticsStripped.pb_aa94bc5179ca8a14f130d6f5ee5a3c26.o)
      _OBJC_METACLASS_$_FIR_CLEARCUTClientInfo_ClientTypeEnumDescriptor in FirebaseAnalytics(ClientanalyticsStripped.pb_aa94bc5179ca8a14f130d6f5ee5a3c26.o)
      _OBJC_METACLASS_$_FIR_CLEARCUTLogRequest_LogSourceEnumDescriptor in FirebaseAnalytics(ClientanalyticsStripped.pb_aa94bc5179ca8a14f130d6f5ee5a3c26.o)
      ...
  "_OBJC_CLASS_$_GSDK_PBRootObject", referenced from:
      _OBJC_CLASS_$_FIR_CLEARCUTClientanalyticsStrippedRoot in FirebaseAnalytics(ClientanalyticsStripped.pb_aa94bc5179ca8a14f130d6f5ee5a3c26.o)
      _OBJC_CLASS_$_ACPGmpAudienceRoot in FirebaseAnalytics(GmpAudience.pb_d68254ec585824fa42de6de2f056cda0.o)
      _OBJC_CLASS_$_ACPGmpConfigRoot in FirebaseAnalytics(GmpConfig.pb_ab1145dc8be746cf062deaba528d2d30.o)
      _OBJC_CLASS_$_ACPGmpMeasurementRoot in FirebaseAnalytics(GmpMeasurement.pb_20d3abd5a5d905507f0986bcf4a2d72c.o)
      _OBJC_CLASS_$_FIR_ICOREIcoreStrippedRoot in FirebaseAnalytics(IcoreStripped.pb_3e848749575206f4cf5f115ea38a4ebe.o)
  "_OBJC_CLASS_$_GSDK_PBObjectivecDescriptorRoot", referenced from:
      objc-class-ref in FirebaseAnalytics(ClientanalyticsStripped.pb_aa94bc5179ca8a14f130d6f5ee5a3c26.o)
      objc-class-ref in FirebaseAnalytics(GmpAudience.pb_d68254ec585824fa42de6de2f056cda0.o)
      objc-class-ref in FirebaseAnalytics(GmpConfig.pb_ab1145dc8be746cf062deaba528d2d30.o)
      objc-class-ref in FirebaseAnalytics(IcoreStripped.pb_3e848749575206f4cf5f115ea38a4ebe.o)
  "_OBJC_CLASS_$_GSDK_PBExtensionRegistry", referenced from:
      objc-class-ref in FirebaseAnalytics(ClientanalyticsStripped.pb_aa94bc5179ca8a14f130d6f5ee5a3c26.o)
      objc-class-ref in FirebaseAnalytics(GmpAudience.pb_d68254ec585824fa42de6de2f056cda0.o)
      objc-class-ref in FirebaseAnalytics(GmpConfig.pb_ab1145dc8be746cf062deaba528d2d30.o)
      objc-class-ref in FirebaseAnalytics(IcoreStripped.pb_3e848749575206f4cf5f115ea38a4ebe.o)
  "_OBJC_METACLASS_$_GSDK_PBRootObject", referenced from:
      _OBJC_METACLASS_$_FIR_CLEARCUTClientanalyticsStrippedRoot in FirebaseAnalytics(ClientanalyticsStripped.pb_aa94bc5179ca8a14f130d6f5ee5a3c26.o)
      _OBJC_METACLASS_$_ACPGmpAudienceRoot in FirebaseAnalytics(GmpAudience.pb_d68254ec585824fa42de6de2f056cda0.o)
      _OBJC_METACLASS_$_ACPGmpConfigRoot in FirebaseAnalytics(GmpConfig.pb_ab1145dc8be746cf062deaba528d2d30.o)
      _OBJC_METACLASS_$_ACPGmpMeasurementRoot in FirebaseAnalytics(GmpMeasurement.pb_20d3abd5a5d905507f0986bcf4a2d72c.o)
      _OBJC_METACLASS_$_FIR_ICOREIcoreStrippedRoot in FirebaseAnalytics(IcoreStripped.pb_3e848749575206f4cf5f115ea38a4ebe.o)
  "_OBJC_CLASS_$_GSDK_PBMutableArray", referenced from:
      objc-class-ref in FirebaseAnalytics(FIRAMeasurement_ae19336699e3b8cd4a19ac2b40344f6c.o)
      objc-class-ref in FirebaseAnalytics(FIRAAudience_cf4210541e4cd915086dc947aea54ec4.o)
  "_GSDK_NSClassFromString", referenced from:
      +[FIRAAppDelegateProxy createSubclassWithObject:] in FirebaseAnalytics(FIRAAppDelegateProxy_30293eb7e3ec49188742bd70c73a43c6.o)
      +[FIRAMeasurement deepLinkFromUserActivity:] in FirebaseAnalytics(FIRAMeasurement_ae19336699e3b8cd4a19ac2b40344f6c.o)
      ___41+[FIRAASIdentifierManager sharedInstance]_block_invoke in FirebaseAnalytics(FIRAASIdentifierManager_f78a22969e29ffea524382ddd57b9514.o)
      +[FIRAnalytics maybeEnableTagManager] in FirebaseAnalytics(FIRAnalytics_b00f7874d695b0305704fe6786f8f2cc.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

**Comment by soheilbm** [comment]
how are you linking the frameworks in your project?

**Comment by kulakoff83** [comment]
Embedded binaries -> +

**Comment by brianlenz** [comment]
I've got a lot more details about this issue in #10.
